global:
  dist-dirs: &dd './dist'
  tsconfig: tsconfig.lib.json

copy-files:
  from:
    - package.json
    - LICENSE
    - CHANGELOG.md
    - README.md
  to: *dd

build:
  targets:
    - cjs
    - declaration
    - fesm5
    - fesm2015
    - esm5
    - esm2015
    - umd
  entry: src/LazyGetter.ts
  license-banner: true
  out: *dd
  umd-name: LazyGet
  externals: tslib
