branch: master
tagFormat: '${version}'

prepare:
- '@semantic-release/changelog'
- '@alorel-personal/semantic-release'
- '@semantic-release/npm'
- path: '@semantic-release/git'
  message: 'chore(release): ${nextRelease.version}'
  assets:
  - CHANGELOG.md
  - README.md
  - package.json
  - yarn.lock

generateNotes:
  config: '@alorel-personal/conventional-changelog-alorel'
