base: &base
  language: node_js
  node_js: 9
  sudo: false
  cache:
    directories:
      - node_modules
  before_script: greenkeeper-lockfile-update
  before_cache: rm -rf ./node_modules/.cache
  after_success: cat ./coverage/lcov.info | coveralls
  before_deploy: npm run build
  script:
    - npm run lint
    - npm test

jobs:
  include:
    - <<: *base
      if: type IN (push, cron)
      env:
        - secure: lrcamRswKcT06gpk6+oQshkkN2MmCAnACu3/yUoxHGeUX2lz8GkwKFFkrr5yhp33yjP0wkblI6WCq0kp+Avx/xNEP+yOr1KPi8RsUU+92deF2+0IImLol+IbTuUU8LzR+UUWrrLJ0A4HxtYhYw37CYkOjoom53YHySVe1RTUxHO4f/9NRBYj7TZcwPBTR2vdF+4twHbEZFW3Gwm4zK0JNDj5QECTIZvN564I3FD+9zHH4+4/05T0WeJXDJjhkz6fvb9wzT15YBr67cYNLsCRvOjC6soMYqWPq3QWpMU5Y3FIXr2xJHbusxIbHWwAVKvSTnkpKfSVonDL8hY/QMNYfVSoFhx1kt79CWHaJDkNCl/U6jBiebZPvBT2JoeblNPGn0AydsqCNhZJ6XCIL1+J0I8HaTvjWlByaitiiuWY7GbevnplZ76g4daQ+xd9c89i51LIQqP0qb6RI1c+P+wlf25SDNEi/ExdhNxnG5nAqM7G3a77n90zAhgypKLmsVGXXYBGOHVKLxcO+rXObGwEVdb2CACeJVl3mI4tFV6R4SUzW+U6kr0yKPFTFva9fPjcdsAPrKNu1hL005ldYvZDzFoQqFpFUoqeR17AANUXDmVWCih5eZ6o8JmessuTg+KM0VrKzLy/6Pr72F1VHY9Y1ExRag55t8JOZ6BzTV8qav8=
      after_script: greenkeeper-lockfile-upload
      deploy:
          provider: npm
          skip_cleanup: true
          email: a.molcanovas@gmail.com
          api_key:
            secure: o2ye1uRdwUUg1sUX/RJf2h9vGLJXwDuh1in2hslKL4llxwyZJmkO+ocuBNP0wCvuX2mYjkzg24ea58ohL/2NkW3re2Wc4fWfzqwtGYjwWogbGO+1JWHIqekVO1ofqaeKagz7pxi28VxviAjAwO9dNTH0QppdJZ1z6BlQ3mtLMAg6dS7DR11TfAkjmG+KX4XCG9d3ERYBc91iOMDFonMS80fPhkLwJH7oCQiNHl+ZOucuLKOXs8lfmVv4wpCvjG9q20YLBZo7JBby/O8B6dORwUgslzLdDS3HCAqLptgJ1r/3oYA79u4WamVO+5ATwdqMwHrsjVIUjhKxiAfAA/pXRb9WQtWvcUlK0s2wiux/RfSZ93OR1Zx68QeJHNU51DOqrSwW0JxztM2Ue6TMlAkwwdltRKrNDAULQIv9kSaQinQFCFl22cuJVU+zaDFXMUf67RBhbyoGyWvTFwWkTWqhujtwgj8AjzfuPyWKBuKx0o2wPxBhK5/y8hgF7NMjDZmk5X18ojaICS5mZV0q0UW6yHlv8XuJiZ+BJmvjGtSR07G5VJtEhERZ08qnsdaASqZJDXobTGmn/CxKN1lvCbbCTojJ2OE+CsKw2MT+Rboq5vnptZfU6uZ6Rx1sWpTKAEkHUn579ocuNBdULR/w+ZNJGwhDLEf58ex6ebKCrF4J6uM=
          on:
            tags: true
            repo: Alorel/typescript-lazy-get-decorator
    - <<: *base
      if: NOT type IN (push, cron)
