language: node_js
node_js:
  - stable
  - lts/*

cache:
  yarn: true

before_install:
  - npm i -g greenkeeper-lockfile yarn
  - greenkeeper-lockfile-update

install: yarn install --check-files --ignore-engines

script:
  - npm run lint
  - npm test

after_success: cat ./coverage/lcov.info | coveralls
after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;

stages:
  - Test
  - name: Release
    if: branch = master AND type = push AND (NOT tag IS present)

jobs:
  include:
    - stage: Release
      node_js: stable
      before_install: npm i -g yarn
      before_script:
        - npm run build
        - alo copy-files
        - alo clean-pkg-json
        - alo clean-dist
      script: semantic-release
      after_success: []
      after_script: []
