#language: node_js
#node_js: 9
#
#env:
#  - secure: lrcamRswKcT06gpk6+oQshkkN2MmCAnACu3/yUoxHGeUX2lz8GkwKFFkrr5yhp33yjP0wkblI6WCq0kp+Avx/xNEP+yOr1KPi8RsUU+92deF2+0IImLol+IbTuUU8LzR+UUWrrLJ0A4HxtYhYw37CYkOjoom53YHySVe1RTUxHO4f/9NRBYj7TZcwPBTR2vdF+4twHbEZFW3Gwm4zK0JNDj5QECTIZvN564I3FD+9zHH4+4/05T0WeJXDJjhkz6fvb9wzT15YBr67cYNLsCRvOjC6soMYqWPq3QWpMU5Y3FIXr2xJHbusxIbHWwAVKvSTnkpKfSVonDL8hY/QMNYfVSoFhx1kt79CWHaJDkNCl/U6jBiebZPvBT2JoeblNPGn0AydsqCNhZJ6XCIL1+J0I8HaTvjWlByaitiiuWY7GbevnplZ76g4daQ+xd9c89i51LIQqP0qb6RI1c+P+wlf25SDNEi/ExdhNxnG5nAqM7G3a77n90zAhgypKLmsVGXXYBGOHVKLxcO+rXObGwEVdb2CACeJVl3mI4tFV6R4SUzW+U6kr0yKPFTFva9fPjcdsAPrKNu1hL005ldYvZDzFoQqFpFUoqeR17AANUXDmVWCih5eZ6o8JmessuTg+KM0VrKzLy/6Pr72F1VHY9Y1ExRag55t8JOZ6BzTV8qav8=

base: &base
  language: node_js
  node_js: 9
  sudo: false
  cache:
    directories:
      - node_modules
  before_script: greenkeeper-lockfile-update
  before_cache: rm -rf ./node_modules/.cache
  after_success: cat ./coverage/lcov.info | coveralls
  before_deploy: npm run build
  script:
    - npm run lint
    - npm test
  deploy:
    provider: npm
    skip_cleanup: true
    email: a.molcanovas@gmail.com
    api_key:
      secure: utzHa6FUzmzcw+K2uBXGENkgDPJuN63gctYddHqZysvzkl7iaRK/b/ZHBiLYf3oODPKEEc9q1cDSoDQlfkumNKCVE6HjjrPcg2PBY5WpE+88slBE9JvVc92EXsxiosPi+TsbqqX5TROZCl3eLhcPuRj/sljwIkEV3bTOePngLO0aPrkkeoHDzw/mDpor2BDvM/2s/GQDSrbjjyoUiZG6/sh8u687k3qgzWWqLBXA4Z2uGemvWOaIaORlBIukMViRSj8cmNwiJT/an8+nAcjRVeFzDtGUljzjtIZ96lts2BjUO5tJi9OCs5I4+svIa4N5lAczxW/sCjs412TIE22+YxmRXH7GRyDF8URtxIGpGA7X2n1Ye26xruBbU2i1yJgzXCFk4dThZDZA6meKNHCzAonn1Vu/Ll1kDgEzXViIkLbZpKAkL+QPqi1tYFvSLqTf/rjmyVkCPdSi+vAWS5emUS32T0xIyERhlIs2y30mvMVcT9X9YHU4F/MPxkgxFzEDU4+J84filEer7N8HeZHNugOh/FUu0iSSQjHjwkhzqhjrPXHpFczNjie53qHYvIzze9K10ONxLfVzEgfeWd332CKwwHde1DTxjWocQdnftIrWCFbUph82GSU/ZCyuHxkGg1pzOnNl2AmDZs17UbbXX4d3qv95MPM/nCMbghwUHXw=
    on:
      tags: true
      repo: Alorel/typescript-lazy-get-decorator

jobs:
  include:
    - <<: *base
      if: type IN (push, cron)
      env:
        - secure: lrcamRswKcT06gpk6+oQshkkN2MmCAnACu3/yUoxHGeUX2lz8GkwKFFkrr5yhp33yjP0wkblI6WCq0kp+Avx/xNEP+yOr1KPi8RsUU+92deF2+0IImLol+IbTuUU8LzR+UUWrrLJ0A4HxtYhYw37CYkOjoom53YHySVe1RTUxHO4f/9NRBYj7TZcwPBTR2vdF+4twHbEZFW3Gwm4zK0JNDj5QECTIZvN564I3FD+9zHH4+4/05T0WeJXDJjhkz6fvb9wzT15YBr67cYNLsCRvOjC6soMYqWPq3QWpMU5Y3FIXr2xJHbusxIbHWwAVKvSTnkpKfSVonDL8hY/QMNYfVSoFhx1kt79CWHaJDkNCl/U6jBiebZPvBT2JoeblNPGn0AydsqCNhZJ6XCIL1+J0I8HaTvjWlByaitiiuWY7GbevnplZ76g4daQ+xd9c89i51LIQqP0qb6RI1c+P+wlf25SDNEi/ExdhNxnG5nAqM7G3a77n90zAhgypKLmsVGXXYBGOHVKLxcO+rXObGwEVdb2CACeJVl3mI4tFV6R4SUzW+U6kr0yKPFTFva9fPjcdsAPrKNu1hL005ldYvZDzFoQqFpFUoqeR17AANUXDmVWCih5eZ6o8JmessuTg+KM0VrKzLy/6Pr72F1VHY9Y1ExRag55t8JOZ6BzTV8qav8=
      after_script: greenkeeper-lockfile-upload
    - <<: *base
      if: NOT type IN (push, cron)
