sudo: false
language: node_js
node_js: 8

cache:
  directories:
    - node_modules

after_success:
  - "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"

before_deploy:
  - npm install -g npm@next
  - npm run generate:npmignore

script:
  - npm run lint
  - npm test

deploy:
  provider: npm
  skip_cleanup: true
  email: a.molcanovas@gmail.com
  api_key:
    secure: utzHa6FUzmzcw+K2uBXGENkgDPJuN63gctYddHqZysvzkl7iaRK/b/ZHBiLYf3oODPKEEc9q1cDSoDQlfkumNKCVE6HjjrPcg2PBY5WpE+88slBE9JvVc92EXsxiosPi+TsbqqX5TROZCl3eLhcPuRj/sljwIkEV3bTOePngLO0aPrkkeoHDzw/mDpor2BDvM/2s/GQDSrbjjyoUiZG6/sh8u687k3qgzWWqLBXA4Z2uGemvWOaIaORlBIukMViRSj8cmNwiJT/an8+nAcjRVeFzDtGUljzjtIZ96lts2BjUO5tJi9OCs5I4+svIa4N5lAczxW/sCjs412TIE22+YxmRXH7GRyDF8URtxIGpGA7X2n1Ye26xruBbU2i1yJgzXCFk4dThZDZA6meKNHCzAonn1Vu/Ll1kDgEzXViIkLbZpKAkL+QPqi1tYFvSLqTf/rjmyVkCPdSi+vAWS5emUS32T0xIyERhlIs2y30mvMVcT9X9YHU4F/MPxkgxFzEDU4+J84filEer7N8HeZHNugOh/FUu0iSSQjHjwkhzqhjrPXHpFczNjie53qHYvIzze9K10ONxLfVzEgfeWd332CKwwHde1DTxjWocQdnftIrWCFbUph82GSU/ZCyuHxkGg1pzOnNl2AmDZs17UbbXX4d3qv95MPM/nCMbghwUHXw=
  on:
    tags: true
    repo: Alorel/typescript-lazy-get-decorator
