name: Set up npm
description: Set up npm and install dependencies
inputs:
  registry-url:
    description: Registry URL
  cache:
    description: Cache to use, if any
  token:
    description: Node auth token
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      name: Set up node
      with:
        node-version-file: .nvmrc
        cache: ${{ inputs.cache }}
        token: ${{ inputs.token }}
        registry-url: ${{ inputs.registry-url }}
